## Preprocessing

In [17]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [18]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df.drop(['NAME'], axis=1, inplace=True)
application_df

,EIN,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...,...
34294,996009318,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,996010315,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,996012607,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,996015768,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,996086871,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [19]:
# Determine the number of unique values in each column.
application_type = application_df.dtypes.index.tolist()
application_df[application_type].nunique()

EIN                       34299
APPLICATION_TYPE             17
AFFILIATION                   6
CLASSIFICATION               71
USE_CASE                      5
ORGANIZATION                  4
STATUS                        2
INCOME_AMT                    9
SPECIAL_CONSIDERATIONS        2
ASK_AMT                    8747
IS_SUCCESSFUL                 2
dtype: int64

In [20]:
# Look at APPLICATION_TYPE value counts for binning
application_counts = application_df['APPLICATION_TYPE'].value_counts()
application_counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [21]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(application_counts[application_counts<300].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [22]:
# Look at CLASSIFICATION value counts for binning
classification_counts = application_df['CLASSIFICATION'].value_counts()
classification_counts

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [23]:
# You may find it helpful to look at CLASSIFICATION value counts >1
application_df['CLASSIFICATION'].value_counts().loc[lambda x : x > 1]

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [24]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(classification_counts[classification_counts<300].index)
# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
Other     1484
C7000      777
Name: CLASSIFICATION, dtype: int64

In [25]:
# Convert categorical data to numeric with `pd.get_dummies`
numeric_df = pd.get_dummies(application_df)
numeric_df

,EIN,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,10520599,1,5000,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,10531628,1,108590,1,0,0,0,1,0,0,...,1,0,0,0,0,0,0,0,1,0
2,10547893,1,5000,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,1,0
3,10553066,1,6692,1,0,0,0,1,0,0,...,0,1,0,0,0,0,0,0,1,0
4,10556103,1,142590,1,0,0,0,1,0,0,...,0,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,996009318,1,5000,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
34295,996010315,1,5000,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
34296,996012607,1,5000,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
34297,996015768,1,5000,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,1,0
34298,996086871,1,36500179,0,0,0,0,1,0,0,...,0,0,0,0,1,0,0,0,1,0

In [26]:
# Split our preprocessed data into our features and target arrays
y = numeric_df["IS_SUCCESSFUL"].values
X = numeric_df.drop(["IS_SUCCESSFUL"], axis=1).values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [27]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [28]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train[0])
hidden_nodes_layer1 =  300
hidden_nodes_layer2 = 200 
hidden_nodes_layer3 = 100
hidden_nodes_layer4 = 50


nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer3, activation="relu"))

nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer4, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_5 (Dense)             (None, 300)               13800

 dense_6 (Dense)             (None, 200)               60200

 dense_7 (Dense)             (None, 100)               20100

 dense_8 (Dense)             (None, 50)                5050

 dense_9 (Dense)             (None, 1)                 51

=================================================================
Total params: 99,201
Trainable params: 99,201
Non-trainable params: 0
_________________________________________________________________

In [29]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [30]:
# Train the model
fit_model = nn.fit(X_train_scaled,y_train,epochs=200)

Epoch 1/200
804/804 [==============================] - 4s 3ms/step - loss: 0.5654 - accuracy: 0.7259
Epoch 2/200
804/804 [==============================] - 3s 3ms/step - loss: 0.5523 - accuracy: 0.7308
Epoch 3/200
804/804 [==============================] - 3s 3ms/step - loss: 0.5490 - accuracy: 0.7332
Epoch 4/200
804/804 [==============================] - 3s 3ms/step - loss: 0.5469 - accuracy: 0.7335
Epoch 5/200
804/804 [==============================] - 2s 3ms/step - loss: 0.5440 - accuracy: 0.7370
Epoch 6/200
804/804 [==============================] - 2s 3ms/step - loss: 0.5428 - accuracy: 0.7365
Epoch 7/200
804/804 [==============================] - 2s 3ms/step - loss: 0.5415 - accuracy: 0.7371
Epoch 8/200
804/804 [==============================] - 3s 3ms/step - loss: 0.5400 - accuracy: 0.7382
Epoch 9/200
804/804 [==============================] - 3s 3ms/step - loss: 0.5382 - accuracy: 0.7385
Epoch 10/200
804/804 [==============================] - 3s 4ms/step - loss: 0.5374 - accuracy: 0.7395
Epoch 11/200
804/804 [==============================] - 3s 4ms/step - loss: 0.5370 - accuracy: 0.7391
Epoch 12/200
804/804 [==============================] - 3s 4ms/step - loss: 0.5347 - accuracy: 0.7406
Epoch 13/200
804/804 [==============================] - 3s 4ms/step - loss: 0.5332 - accuracy: 0.7426
Epoch 14/200
804/804 [==============================] - 3s 4ms/step - loss: 0.5323 - accuracy: 0.7432
Epoch 15/200
804/804 [==============================] - 3s 4ms/step - loss: 0.5319 - accuracy: 0.7427
Epoch 16/200
804/804 [==============================] - 3s 4ms/step - loss: 0.5305 - accuracy: 0.7432
Epoch 17/200
804/804 [==============================] - 3s 4ms/step - loss: 0.5302 - accuracy: 0.7434
Epoch 18/200
804/804 [==============================] - 3s 4ms/step - loss: 0.5291 - accuracy: 0.7453
Epoch 19/200
804/804 [==============================] - 3s 4ms/step - loss: 0.5276 - accuracy: 0.7457
Epoch 20/200
804/804 [==============================] - 3s 4ms/step - loss: 0.5266 - accuracy: 0.7445
Epoch 21/200
804/804 [==============================] - 3s 4ms/step - loss: 0.5269 - accuracy: 0.7456
Epoch 22/200
804/804 [==============================] - 3s 4ms/step - loss: 0.5254 - accuracy: 0.7456
Epoch 23/200
804/804 [==============================] - 3s 4ms/step - loss: 0.5241 - accuracy: 0.7472
Epoch 24/200
804/804 [==============================] - 3s 4ms/step - loss: 0.5234 - accuracy: 0.7469
Epoch 25/200
804/804 [==============================] - 3s 4ms/step - loss: 0.5232 - accuracy: 0.7485
Epoch 26/200
804/804 [==============================] - 3s 3ms/step - loss: 0.5232 - accuracy: 0.7475
Epoch 27/200
804/804 [==============================] - 3s 3ms/step - loss: 0.5227 - accuracy: 0.7479
Epoch 28/200
804/804 [==============================] - 2s 3ms/step - loss: 0.5214 - accuracy: 0.7495
Epoch 29/200
804/804 [==============================] - 3s 3ms/step - loss: 0.5196 - accuracy: 0.7505
Epoch 30/200
804/804 [==============================] - 3s 3ms/step - loss: 0.5183 - accuracy: 0.7498
Epoch 31/200
804/804 [==============================] - 3s 3ms/step - loss: 0.5184 - accuracy: 0.7496
Epoch 32/200
804/804 [==============================] - 3s 3ms/step - loss: 0.5184 - accuracy: 0.7510
Epoch 33/200
804/804 [==============================] - 3s 3ms/step - loss: 0.5174 - accuracy: 0.7510
Epoch 34/200
804/804 [==============================] - 3s 3ms/step - loss: 0.5169 - accuracy: 0.7515
Epoch 35/200
804/804 [==============================] - 3s 3ms/step - loss: 0.5155 - accuracy: 0.7518
Epoch 36/200
804/804 [==============================] - 3s 3ms/step - loss: 0.5154 - accuracy: 0.7510
Epoch 37/200
804/804 [==============================] - 3s 3ms/step - loss: 0.5158 - accuracy: 0.7519
Epoch 38/200
804/804 [==============================] - 3s 3ms/step - loss: 0.5136 - accuracy: 0.7526
Epoch 39/200
804/804 [==============================] - 2s 3ms/step - loss: 0.5148 - accuracy: 0.7524
Epoch 40/200
804/804 [==============================] - 3s 3ms/step - loss: 0.5126 - accuracy: 0.7527
Epoch 41/200
804/804 [==============================] - 2s 3ms/step - loss: 0.5129 - accuracy: 0.7524
Epoch 42/200
804/804 [==============================] - 3s 3ms/step - loss: 0.5124 - accuracy: 0.7537
Epoch 43/200
804/804 [==============================] - 3s 3ms/step - loss: 0.5113 - accuracy: 0.7524
Epoch 44/200
804/804 [==============================] - 3s 3ms/step - loss: 0.5109 - accuracy: 0.7545
Epoch 45/200
804/804 [==============================] - 3s 3ms/step - loss: 0.5111 - accuracy: 0.7526
Epoch 46/200
804/804 [==============================] - 3s 3ms/step - loss: 0.5123 - accuracy: 0.7498
Epoch 47/200
804/804 [==============================] - 3s 3ms/step - loss: 0.5094 - accuracy: 0.7538
Epoch 48/200
804/804 [==============================] - 3s 3ms/step - loss: 0.5087 - accuracy: 0.7532
Epoch 49/200
804/804 [==============================] - 3s 3ms/step - loss: 0.5080 - accuracy: 0.7550
Epoch 50/200
804/804 [==============================] - 3s 3ms/step - loss: 0.5091 - accuracy: 0.7544
Epoch 51/200
804/804 [==============================] - 3s 3ms/step - loss: 0.5075 - accuracy: 0.7548
Epoch 52/200
804/804 [==============================] - 3s 3ms/step - loss: 0.5065 - accuracy: 0.7558
Epoch 53/200
804/804 [==============================] - 3s 3ms/step - loss: 0.5061 - accuracy: 0.7554
Epoch 54/200
804/804 [==============================] - 3s 3ms/step - loss: 0.5051 - accuracy: 0.7549
Epoch 55/200
804/804 [==============================] - 3s 3ms/step - loss: 0.5071 - accuracy: 0.7537
Epoch 56/200
804/804 [==============================] - 2s 3ms/step - loss: 0.5054 - accuracy: 0.7552
Epoch 57/200
804/804 [==============================] - 2s 3ms/step - loss: 0.5056 - accuracy: 0.7548
Epoch 58/200
804/804 [==============================] - 2s 3ms/step - loss: 0.5070 - accuracy: 0.7562
Epoch 59/200
804/804 [==============================] - 2s 3ms/step - loss: 0.5044 - accuracy: 0.7568
Epoch 60/200
804/804 [==============================] - 3s 3ms/step - loss: 0.5032 - accuracy: 0.7579
Epoch 61/200
804/804 [==============================] - 3s 3ms/step - loss: 0.5044 - accuracy: 0.7566
Epoch 62/200
804/804 [==============================] - 3s 3ms/step - loss: 0.5022 - accuracy: 0.7579
Epoch 63/200
804/804 [==============================] - 3s 3ms/step - loss: 0.5036 - accuracy: 0.7572
Epoch 64/200
804/804 [==============================] - 3s 3ms/step - loss: 0.5027 - accuracy: 0.7568
Epoch 65/200
804/804 [==============================] - 3s 3ms/step - loss: 0.5022 - accuracy: 0.7580
Epoch 66/200
804/804 [==============================] - 3s 3ms/step - loss: 0.5031 - accuracy: 0.7573
Epoch 67/200
804/804 [==============================] - 3s 3ms/step - loss: 0.5022 - accuracy: 0.7570
Epoch 68/200
804/804 [==============================] - 2s 3ms/step - loss: 0.5013 - accuracy: 0.7574
Epoch 69/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4996 - accuracy: 0.7576
Epoch 70/200
804/804 [==============================] - 2s 3ms/step - loss: 0.5000 - accuracy: 0.7577
Epoch 71/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4989 - accuracy: 0.7570
Epoch 72/200
804/804 [==============================] - 3s 3ms/step - loss: 0.5012 - accuracy: 0.7583
Epoch 73/200
804/804 [==============================] - 3s 3ms/step - loss: 0.5012 - accuracy: 0.7587
Epoch 74/200
804/804 [==============================] - 2s 3ms/step - loss: 0.4977 - accuracy: 0.7593
Epoch 75/200
804/804 [==============================] - 3s 3ms/step - loss: 0.5004 - accuracy: 0.7590
Epoch 76/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4977 - accuracy: 0.7592
Epoch 77/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4978 - accuracy: 0.7592
Epoch 78/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4990 - accuracy: 0.7585
Epoch 79/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4995 - accuracy: 0.7583
Epoch 80/200
804/804 [==============================] - 3s 3ms/step - loss: 0.5013 - accuracy: 0.7598
Epoch 81/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4992 - accuracy: 0.7592
Epoch 82/200
804/804 [==============================] - 2s 3ms/step - loss: 0.4991 - accuracy: 0.7568
Epoch 83/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4966 - accuracy: 0.7592
Epoch 84/200
804/804 [==============================] - 3s 3ms/step - loss: 0.5005 - accuracy: 0.7600
Epoch 85/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4975 - accuracy: 0.7589
Epoch 86/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4974 - accuracy: 0.7590
Epoch 87/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4961 - accuracy: 0.7594
Epoch 88/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4976 - accuracy: 0.7599
Epoch 89/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4969 - accuracy: 0.7614
Epoch 90/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4944 - accuracy: 0.7600
Epoch 91/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4945 - accuracy: 0.7602
Epoch 92/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4943 - accuracy: 0.7601
Epoch 93/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4964 - accuracy: 0.7596
Epoch 94/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4942 - accuracy: 0.7605
Epoch 95/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4938 - accuracy: 0.7602
Epoch 96/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4941 - accuracy: 0.7604
Epoch 97/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4958 - accuracy: 0.7594
Epoch 98/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4927 - accuracy: 0.7614
Epoch 99/200
804/804 [==============================] - 4s 4ms/step - loss: 0.4933 - accuracy: 0.7604
Epoch 100/200
804/804 [==============================] - 4s 5ms/step - loss: 0.4930 - accuracy: 0.7609
Epoch 101/200
804/804 [==============================] - 4s 5ms/step - loss: 0.4920 - accuracy: 0.7604
Epoch 102/200
804/804 [==============================] - 3s 4ms/step - loss: 0.4925 - accuracy: 0.7592
Epoch 103/200
804/804 [==============================] - 3s 4ms/step - loss: 0.4926 - accuracy: 0.7618
Epoch 104/200
804/804 [==============================] - 3s 4ms/step - loss: 0.4922 - accuracy: 0.7604
Epoch 105/200
804/804 [==============================] - 3s 4ms/step - loss: 0.4918 - accuracy: 0.7601
Epoch 106/200
804/804 [==============================] - 3s 4ms/step - loss: 0.4915 - accuracy: 0.7607
Epoch 107/200
804/804 [==============================] - 3s 4ms/step - loss: 0.4914 - accuracy: 0.7614
Epoch 108/200
804/804 [==============================] - 3s 4ms/step - loss: 0.5242 - accuracy: 0.7598
Epoch 109/200
804/804 [==============================] - 3s 4ms/step - loss: 0.4945 - accuracy: 0.7601
Epoch 110/200
804/804 [==============================] - 3s 4ms/step - loss: 0.4890 - accuracy: 0.7617
Epoch 111/200
804/804 [==============================] - 3s 4ms/step - loss: 0.4903 - accuracy: 0.7610
Epoch 112/200
804/804 [==============================] - 3s 4ms/step - loss: 0.4888 - accuracy: 0.7625
Epoch 113/200
804/804 [==============================] - 3s 4ms/step - loss: 0.4892 - accuracy: 0.7612
Epoch 114/200
804/804 [==============================] - 3s 4ms/step - loss: 0.4882 - accuracy: 0.7624
Epoch 115/200
804/804 [==============================] - 3s 4ms/step - loss: 0.4879 - accuracy: 0.7621
Epoch 116/200
804/804 [==============================] - 3s 4ms/step - loss: 0.4948 - accuracy: 0.7616
Epoch 117/200
804/804 [==============================] - 3s 4ms/step - loss: 0.4894 - accuracy: 0.7625
Epoch 118/200
804/804 [==============================] - 3s 4ms/step - loss: 0.4891 - accuracy: 0.7620
Epoch 119/200
804/804 [==============================] - 3s 4ms/step - loss: 0.4891 - accuracy: 0.7612
Epoch 120/200
804/804 [==============================] - 3s 4ms/step - loss: 0.4878 - accuracy: 0.7622
Epoch 121/200
804/804 [==============================] - 3s 4ms/step - loss: 0.4888 - accuracy: 0.7626
Epoch 122/200
804/804 [==============================] - 3s 4ms/step - loss: 0.4900 - accuracy: 0.7633
Epoch 123/200
804/804 [==============================] - 3s 4ms/step - loss: 0.4882 - accuracy: 0.7627
Epoch 124/200
804/804 [==============================] - 3s 4ms/step - loss: 0.4887 - accuracy: 0.7616
Epoch 125/200
804/804 [==============================] - 3s 4ms/step - loss: 0.4900 - accuracy: 0.7622
Epoch 126/200
804/804 [==============================] - 3s 4ms/step - loss: 0.4883 - accuracy: 0.7630
Epoch 127/200
804/804 [==============================] - 3s 4ms/step - loss: 0.4887 - accuracy: 0.7628
Epoch 128/200
804/804 [==============================] - 3s 4ms/step - loss: 0.4885 - accuracy: 0.7637
Epoch 129/200
804/804 [==============================] - 3s 4ms/step - loss: 0.4896 - accuracy: 0.7617
Epoch 130/200
804/804 [==============================] - 3s 4ms/step - loss: 0.4888 - accuracy: 0.7621
Epoch 131/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4874 - accuracy: 0.7629
Epoch 132/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4868 - accuracy: 0.7640
Epoch 133/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4878 - accuracy: 0.7632
Epoch 134/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4863 - accuracy: 0.7631
Epoch 135/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4879 - accuracy: 0.7640
Epoch 136/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4897 - accuracy: 0.7625
Epoch 137/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4866 - accuracy: 0.7635
Epoch 138/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4856 - accuracy: 0.7636
Epoch 139/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4870 - accuracy: 0.7640
Epoch 140/200
804/804 [==============================] - 2s 3ms/step - loss: 0.4867 - accuracy: 0.7638
Epoch 141/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4885 - accuracy: 0.7628
Epoch 142/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4901 - accuracy: 0.7628
Epoch 143/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4923 - accuracy: 0.7625
Epoch 144/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4866 - accuracy: 0.7642
Epoch 145/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4872 - accuracy: 0.7634
Epoch 146/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4884 - accuracy: 0.7642
Epoch 147/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4868 - accuracy: 0.7638
Epoch 148/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4858 - accuracy: 0.7629
Epoch 149/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4865 - accuracy: 0.7636
Epoch 150/200
804/804 [==============================] - 2s 3ms/step - loss: 0.4860 - accuracy: 0.7638
Epoch 151/200
804/804 [==============================] - 2s 3ms/step - loss: 0.4855 - accuracy: 0.7648
Epoch 152/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4853 - accuracy: 0.7639
Epoch 153/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4840 - accuracy: 0.7642
Epoch 154/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4888 - accuracy: 0.7638
Epoch 155/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4853 - accuracy: 0.7651
Epoch 156/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4839 - accuracy: 0.7642
Epoch 157/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4836 - accuracy: 0.7645
Epoch 158/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4846 - accuracy: 0.7645
Epoch 159/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4835 - accuracy: 0.7639
Epoch 160/200

804/804 [==============================] - 3s 3ms/step - loss: 0.4882 - accuracy: 0.7644
Epoch 161/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4829 - accuracy: 0.7650
Epoch 162/200
804/804 [==============================] - 2s 3ms/step - loss: 0.4848 - accuracy: 0.7640
Epoch 163/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4863 - accuracy: 0.7617
Epoch 164/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4848 - accuracy: 0.7642
Epoch 165/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4822 - accuracy: 0.7645
Epoch 166/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4824 - accuracy: 0.7647
Epoch 167/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4820 - accuracy: 0.7656
Epoch 168/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4829 - accuracy: 0.7642
Epoch 169/200
804/804 [==============================] - 2s 3ms/step - loss: 0.4846 - accuracy: 0.7647
Epoch 170/200
804/804 [==============================] - 2s 3ms/step - loss: 0.5019 - accuracy: 0.7629
Epoch 171/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4830 - accuracy: 0.7658
Epoch 172/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4808 - accuracy: 0.7662
Epoch 173/200
804/804 [==============================] - 2s 3ms/step - loss: 0.4828 - accuracy: 0.7647
Epoch 174/200
804/804 [==============================] - 2s 3ms/step - loss: 0.4824 - accuracy: 0.7661
Epoch 175/200
804/804 [==============================] - 3s 3ms/step - loss: 0.5253 - accuracy: 0.7631
Epoch 176/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4880 - accuracy: 0.7629
Epoch 177/200
804/804 [==============================] - 2s 3ms/step - loss: 0.4805 - accuracy: 0.7655
Epoch 178/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4788 - accuracy: 0.7674
Epoch 179/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4792 - accuracy: 0.7673
Epoch 180/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4787 - accuracy: 0.7664
Epoch 181/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4813 - accuracy: 0.7665
Epoch 182/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4810 - accuracy: 0.7656
Epoch 183/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4790 - accuracy: 0.7672
Epoch 184/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4801 - accuracy: 0.7662
Epoch 185/200
804/804 [==============================] - 2s 3ms/step - loss: 0.4812 - accuracy: 0.7665
Epoch 186/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4803 - accuracy: 0.7673
Epoch 187/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4802 - accuracy: 0.7661
Epoch 188/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4805 - accuracy: 0.7655
Epoch 189/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4807 - accuracy: 0.7656
Epoch 190/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4813 - accuracy: 0.7650
Epoch 191/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4824 - accuracy: 0.7657
Epoch 192/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4809 - accuracy: 0.7656
Epoch 193/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4848 - accuracy: 0.7647
Epoch 194/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4819 - accuracy: 0.7653
Epoch 195/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4820 - accuracy: 0.7653
Epoch 196/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4802 - accuracy: 0.7666
Epoch 197/200
804/804 [==============================] - 2s 3ms/step - loss: 0.4821 - accuracy: 0.7642
Epoch 198/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4818 - accuracy: 0.7640
Epoch 199/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4792 - accuracy: 0.7664
Epoch 200/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4822 - accuracy: 0.7659

In [31]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.7525 - accuracy: 0.7275 - 746ms/epoch - 3ms/step
Loss: 0.752470850944519, Accuracy: 0.7274635434150696

In [32]:
# Export our model to HDF5 file
nn.save('AlphabetSoupCharity_Optimization1.h5')